//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_Hasta_Takip_Sistemi_163301012.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SohatsContext : DbContext
    {
        public SohatsContext()
            : base("name=SohatsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cikis> Cikis { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<Islem> Islem { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Poliklinik> Poliklinik { get; set; }
        public virtual DbSet<Sevk> Sevk { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
